# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThreeSDK_Mob_GoogleFacebookTwitterLine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'mob_sharesdk'
  pod 'mob_sharesdk/ShareSDKPlatforms/Facebook'
  pod 'mob_sharesdk/ShareSDKPlatforms/GooglePlus'

end
